name: purepdf
description: A clean, minimal PDF reader for Android with no ads, no tracking, and full offline functionality.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # PDF viewing with native performance
  pdfx: ^2.6.0
  
  # Native file picker for PDF selection
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # App metadata
  name: PurePDF
  description: Clean PDF Reader

# Android specific configuration
flutter:
  android:
    min_sdk_version: 21
    target_sdk_version: 34
    compile_sdk_version: 34
